# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180426_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='bio',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='You in 60 words.'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='totos',
            field=models.IntegerField(default=0, verbose_name='Contribution'),
        ),
    ]
