# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-18 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import write.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Toto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=150)),
                ('cover_photo', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=write.models.upload_location, width_field='width_field')),
                ('photo1', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=write.models.upload_location, width_field='width_field')),
                ('photo2', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=write.models.upload_location, width_field='width_field')),
                ('photo3', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=write.models.upload_location, width_field='width_field')),
                ('photo4', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=write.models.upload_location, width_field='width_field')),
                ('photo5', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=write.models.upload_location, width_field='width_field')),
                ('photo6', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=write.models.upload_location, width_field='width_field')),
                ('photo7', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=write.models.upload_location, width_field='width_field')),
                ('photo8', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=write.models.upload_location, width_field='width_field')),
                ('photo9', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=write.models.upload_location, width_field='width_field')),
                ('photo10', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=write.models.upload_location, width_field='width_field')),
                ('text1', models.TextField(blank=True, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
                ('text3', models.TextField(blank=True, null=True)),
                ('text4', models.TextField(blank=True, null=True)),
                ('text5', models.TextField(blank=True, null=True)),
                ('text6', models.TextField(blank=True, null=True)),
                ('text7', models.TextField(blank=True, null=True)),
                ('text8', models.TextField(blank=True, null=True)),
                ('text9', models.TextField(blank=True, null=True)),
                ('text10', models.TextField(blank=True, null=True)),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('draft', models.BooleanField(default=False)),
                ('publish', models.DateTimeField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-last_updated'],
            },
        ),
    ]
