# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-22 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0002_auto_20170922_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toto',
            name='publish',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
