# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0004_auto_20170923_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toto',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='text10',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='text11',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='text12',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='text13',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='text14',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='text15',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='text3',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='text4',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='text5',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='text6',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='text7',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='text8',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='text9',
        ),
    ]
