# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0005_auto_20171117_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toto',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='photo10',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='photo11',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='photo12',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='photo13',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='photo14',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='photo15',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='photo6',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='photo7',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='photo8',
        ),
        migrations.RemoveField(
            model_name='toto',
            name='photo9',
        ),
    ]
