# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write', '0007_auto_20180309_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toto',
            name='content',
            field=models.TextField(max_length=9999999),
        ),
    ]
